apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crypto-analytics

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - zookeeper.yaml
  - kafka.yaml
  - binance-producer.yaml
  - coingecko-producer.yaml
  - kafka-processor.yaml
  - crypto-api.yaml
  - monitoring.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  project: crypto-stream-analytics
  environment: production
